### PR TITLE
Windows concurrency

### PR DESCRIPTION
**Pull request by techalchemy**
* I added some helper functions but essential the issue on windows boiled down to a problem with paths
* I don't think it's safe to explicitly use forward or backward slashes rather than `os.path.join()`
* There are places where we are currently using `os.sep` and concatenating -- is there a reason? Should we switch to `os.path.join`?
* `Project` objects currently resolve virtualenv locations using forward slashes on windows, but `os.path.join` just appends the remaining items with the normal path separator, so we can use `os.path.normpath` to normalize
* However this pre-escapes the path for us which means we can't drop the command into a double-quoted string and pass it to delegator, so instead I am shellquoting everything that isn't handled this way now

Lets see if it passes tests.

### CODE REVIEW

**Comment by techalchemy** [comment]
well shit, broke appveyor

**Comment by techalchemy** [comment]
JK appveyor was broken already

**Comment by kennethreitz** [comment]
let's get windows tests working first

**Comment by kennethreitz** [comment]
got merge conflict handled

**Comment by kennethreitz** [comment]
running windows tests now

**Comment by kennethreitz** [comment]
looks like they're passing! This will require some additional work.

**Comment by kennethreitz** [comment]
e.g. they're still running non-concurrently.

**Pull request merged**
