### PR TITLE
remove PIPENV_MAX_DEPTH workaround

### PR DESCRIPTION
**Pull request by ofek**
@kennethreitz I'm *fairly* certain I fixed this in https://github.com/pypa/pipfile/pull/83

### CODE REVIEW

**Comment by kennethreitz** [comment]
we didnt' merge that yet.

**Comment by kennethreitz** [comment]
you need to update our vendored pipfile library as well.

**Comment by kennethreitz** [comment]
updated it myself :)

**Comment by kennethreitz** [comment]
had to revert this — broke things

**Comment by ofek** [comment]
What did it break?

**Pull request merged**
