### PR TITLE
Fix popen_spawn when specifying a path on Windows which contains "\" separators

### PR DESCRIPTION
**Pull request by eli-b**
I've opened an identical PR for pexpect: https://github.com/pexpect/pexpect/pull/446

### CODE REVIEW

**Comment by kennethreitz** [comment]
what exactly does this do?

**Comment by kennethreitz** [comment]
everything is behaving as expected right now.

**Comment by eli-b** [comment]
This lets me run `pipenv install --three --python=C:\Miniconda2\envs\python3\python.exe -d` on Windows without getting `WindowsError: [Error 2] The system cannot find the file specified`. `shlex.split` without `posix=False` treats backslashes as escapes instead of preserving them.

There's an [open StackOverflow question](https://stackoverflow.com/questions/41185376/windowserror-error-2-the-system-cannot-find-the-file-specified-in-pexpect-pop/46248216#46248216) about this issue in popen_expect.

I should have explained the problem this solves for me.

**Comment by uranusjr** [comment]
Is `posix=(os.sep == '/')` maybe a more pragmatic solution?

**Comment by techalchemy** [comment]
given that we are specifically interested in whether we are dealing with a posix compliant platform I would recommend `posix=(os.name == 'posix')`

**Comment by eli-b** [comment]
I just copied the test from earlier in the function where `sys.platform == 'win32` is used. Testing for a POSIX system directly might be clearer.

**Comment by techalchemy** [comment]
I have a slight change to this over in #570 for reference

**Pull request merged**
