### PR TITLE
Use clicks feature for terminal colors

### PR DESCRIPTION
**Pull request by timofurrer**
Don't get me wrong @kennethreitz I really do like crayons. It has a much better API than click has for the colors. 

However, my situation is the following: I work with Python in a regulated environment which basically means every third-party dependency has to be documented, validated and maintained (mirroring) (for up to 15 years). Especially for a project like `pipenv` (which might become very essential to the Python ecosystem, I hope) I'd love to see it with as few dependencies as possible but with as much that no code has to be duplicated. In the `crayons` case ... `click` already comes with support for terminal colors so it would be very cheap to use those.

And as I said, I'd much rather use crayons if it would only be about the API - but it isn't. Think about it ;)

### CODE REVIEW

**Comment by kennethreitz** [comment]
sticking to crayons, but i appreciate the work!

**Comment by timofurrer** [comment]
For what reason if I may ask?

**Comment by kennethreitz** [comment]
because i published the library just for this project :)

**Comment by kennethreitz** [comment]
I'd much rather see us vendor it in if needed.

**Comment by kennethreitz** [comment]
As we would then do with all dependencies.

**Comment by timofurrer** [comment]
> because i published the library just for this project :)

Well, yeah, that would be too bad to remove it.

Vendor in sounds look a feasible plan ;) Thanks!

**Pull request closed without merging**
