### PR TITLE
fix for #925

### PR DESCRIPTION
**Pull request by Dreamersoul**
new line is now being added to the end of the toml file

### CODE REVIEW

**Comment by nateprewitt** [comment]
Hey @Dreamersoul, it looks like you've included some unrelated tests in this PR. While we'd love to have those, can you please move them to a separate PR?

Also getting a test for the newline case so this doesn't break again would be great. Thanks!

**Comment by erinxocon** [comment]
Concur with @nateprewitt.  If you can split the tests into another PR that'd be great!

**Comment by Dreamersoul** [comment]
done 👍  currently writing a test for the new line case

**Comment by nateprewitt** [comment]
This looks good to me, thanks @Dreamersoul! We'll merge once the tests finish.

**Comment by Dreamersoul** [comment]
awesome! thank you for keeping up with me 😄  you guys are awesome collaborators @nateprewitt @erinxocon

**Comment by nateprewitt** [comment]
Sorry @Dreamersoul, looks like there's a conflict now due to another merge. Would you mind rebasing onto the current master branch?

**Comment by Dreamersoul** [comment]
thanks for merging 👍

**Comment by erinxocon** [comment]
Thanks @Dreamersoul!

**Pull request merged**
