### PR TITLE
respect pip configuration at Pipfile creation

### PR DESCRIPTION
**Pull request by hrbonz**
Respect pip index configuration (pip.conf or environment variable) when
creating a new Pipfile.

I'm really not sure about this implementation but I wanted to start the conversation, I've made some choices that I think have a minimal impact.

I couldn't find a convenient method in the `pip` project that would just hand me out the best option and respect the configuration precedence so I implemented it by hand.

Change mentioned in #856

### CODE REVIEW

**Comment by hrbonz** [comment]
I feel like I should add some tests here

**Comment by techalchemy** [comment]
Hey @hrbonz thanks for putting this together. Unfortunately altering which source is added to the Pipfile doesn’t quite respect `pip.conf` because of the way pip already generates its repository index list (which already should respect `pip.conf`) and because of the way the piptools resolver works (which isn’t affected by the `Pipfile`).

**Comment by hrbonz** [comment]
@techalchemy unfotunately, `pip.conf` is not respected because of the configuration precedence and the use of [sources](https://github.com/kennethreitz/pipenv/blob/master/pipenv/cli.py#L1400) [as indexes on the command line](https://github.com/kennethreitz/pipenv/blob/master/pipenv/utils.py#L374) with `-i`/`--index-url` or `--extra-index-url`.

That is the base of the issue I described in #856

**Comment by techalchemy** [comment]
@hrbonz I see what you're saying, but I'm not actually sure this is the right approach here.  It's not clear that we actually want to always fall back to the default indexes in the host pip config, since I'm not sure that provides sufficient portability.  I do think we would want to respect environment settings, however, but I think there is some discussion to have here (e.g. in #988 this came up)

We have broader design questions to answer but for now, I would be much more prepared to accept something that prioritizes environment level settings (e.g. `PIP_INDEX_URL` followed by an iterative list over `PIP_EXTRA_INDEX_URL`) -- this approach will probably need to take into account `verify_ssl` from the `PIP_TRUSTED_HOST` environment variable

**Comment by techalchemy** [comment]
And before you rework, /cc @nateprewitt would you be willing to approve a PR to use `PIP_INDEX_URL` from the environment if it exists as the primary pip index (i.e. first entry in `[[sources]]` in the Pipfile?  This seems like something that might impact existing users so I would want a second set of eyes on it

**Comment by kennethreitz** [comment]
We should honor the environment variable instead.

**Comment by kennethreitz** [comment]
not today, but thank you

**Comment by hrbonz** [comment]
There must be something I don't get, why force users to set an environment variable when there is already a configuration for a standard tool that gives you this information? This is, moreover, the tool you use under the hood.
Environment variables are useful in some situations but really not ideal most of the time.

**Pull request closed without merging**
