### PR TITLE
create Pipfile from requirements.txt without installing

### PR DESCRIPTION
**Pull request by nateprewitt**
This PR is to address the issue pointed out in #342.

The install process is dependent upon the virtualenv existing which isn't always the case for fresh projects. This is the most common case this code will execute in, so we need to be able to create the Pipfile before the virtualenv is created. This will read the contents of the requirements.txt file and write them directly into a new Pipfile.

This approach required a little reworking of your initial implementation @kennethreitz, so I'd like you to sign off on this.

I removed the install portion completely because not only was it broken, but I don't know if it makes sense to install with *any* command passed to pipenv. Things like `pipenv shell` and `pipenv check` currently install the requirements.txt into the new environment which probably isn't what the user would expect.

I also removed the `BAD_PACKAGES` check because it *seems* to have been put in place to handle the fact those packages are always returned by `pip freeze`. If the user explicitly defines something like `appdirs` at a specific version in their requirements.txt file, I feel like we should move that to the Pipfile. They felt strongly enough to make it a requirement, so let's not silently delete it.

### CODE REVIEW

**Comment by kennethreitz** [comment]
That's fine, but we need to strip comments from the requirements files. Installing avoids all of that.

**Comment by nateprewitt** [comment]
@kennethreitz I think we should be handling that [here](https://github.com/kennethreitz/pipenv/pull/347/files#diff-e1e68886e05fef92bb74ed1699e5179eR110). I'm reading over the requirements.txt spec now and I may need to expand that check slightly. Pending that, I think this will be as permissive as the install option.

**Comment by kennethreitz** [comment]
Have to be more careful of lines that have `#` after the requirement.

**Comment by nateprewitt** [comment]
@kennethreitz Yep, we need expand the check to be stripping inline comments. I'll work on reintegrating the `BAD_PACKAGES` stripping too.

**Comment by kennethreitz** [comment]
\o/

**Comment by kennethreitz** [comment]
Basically, I want to err on the side of removing them, then revisiting that if people have problems.

**Comment by nateprewitt** [comment]
Alright, this should be good to go. Feel free to merge if you don't have any further feedback or I will this afternoon.

**Comment by kennethreitz** [comment]
✨🍰✨

**Pull request merged**
