### PR TITLE
Prevent invalid shebangs with Homebrew Python

### PR DESCRIPTION
**Pull request by jacebrowning**
Fixes https://github.com/kennethreitz/pipenv/issues/98

### CODE REVIEW

**Comment by nateprewitt** [comment]
Glad you got to the bottom of this @jacebrowning! One thing that may be important here is to make this toggleable rather than always forcing the stripping. Is it possible someone is depending on this variable and `pipenv` will still work, or will `pipenv` always fail when this is present?

**Comment by jacebrowning** [comment]
@nateprewitt From my testing, the only behavior this variable seems to control is the contents of the shebang line in installed scripts. I believe that pipenv's logic is already correctly locating the Python binary in the virtual environment, thus the value of this variable can be ignored.

**Comment by jacebrowning** [comment]
It looks like tox did the exact same thing: https://bitbucket.org/hpk42/tox/pull-requests/118/fix-__pyvenv_launcher__-problem/diff

**Comment by volkanunsal** [comment]
Hello, there may be a reversion. I'm seeing this exact issue in version 0.5.0. The same one described in #98.

**Pull request merged**
