### PR TITLE
Enables more environment variables for scriptability

### PR DESCRIPTION
**Pull request by isaacsanders**
- Adds environment variables for passing in executables (virtualenv,
  pew)
- Adds project root to list of environment variables
- Changes cwd when passing in a root path

### CODE REVIEW

**Comment by kennethreitz** [comment]
i'm generally in favor of having fewer configuration variables, not more. i'll have to think about this. @nateprewitt any thoughts?

**Comment by isaacsanders** [comment]
I wouldn't mind command line switches, but `PIPENV_PIPFILE` matches `BUNDLE_GEMFILE` for example.

The executables are there because I didn't seem to have a way to add them to the path via ssh-oneliner. I could just be wrong.

**Comment by nateprewitt** [comment]
Hey @isaacsanders, thanks for taking the time to put this together. So, I'm a little confused as to why these are needed. Could you describe your scenario a bit more in depth? My current thought process is in line with @kennethreitz, that we probably don't want to expand environment params here.

The executables should be installed on the path if your remote server has python and pipenv installed properly. What is the goal of adding the custom paths?

As for `PIPENV_ROOT`, I'm not sure I understand this one either. This would limit pipenv to only being usable on one project. That, in most cases, probably isn't what a user would want. Especially if you run a non-idempotent command expecting it in your current directory, but your forgotten environment variable navigates to another directory.

I'm definitely open to hearing more detail here, but that's my initial reaction. We really do appreciate you taking the time to put this together though :)

**Comment by isaacsanders** [comment]
Ok, removed the executable stuff. After trying some more things with different configurations, I realized I didn't need these to do what I was looking for.

As for the project root, it allows me to write crontab entries or ssh scripts that either run a script in the environment or install the environment on deploy. I am a Python neophyte, and don't know the intricacies of these other tools, which is why I have chosen to use pipenv. Being able to declare the environment I am using statically is something that is important to my use case.

**Comment by nateprewitt** [comment]
So I would say that `cd $PROJECT_PATH && pipenv COMMAND <xyz>` is an equally as easy since you're modifying the bash environment already. This seems like an edge case which also has some possibly subtle "gotchas". That's keeping me leaning towards passing on this.

**Comment by isaacsanders** [comment]
Ok. That works. I appreciate the help in illuminating my ignorance or <whatever the word is for not seeing a solution because you are focused on a certain level of technology>.

**Pull request closed without merging**
