### PR TITLE
Add fix for windows paths

### LINKED ISSUE #865: Pipenv breaks on Windows paths with spaces.
```bash
Micaiah Parker@COMPUTERNAME MINGW64 ~
$ cd project/

Micaiah Parker@COMPUTERNAME MINGW64 ~/project (master)
$ pipenv install --dev pytest
Installing pytest▒

Error:  An error occurred while installing pytest!
'C:\Users\Micaiah' is not recognized as an internal or external command,
operable program or batch file.
```

I noticed that `utils` does have a `get_windows_path`, but I couldn't find where it is being used.

### PR DESCRIPTION
**Pull request by techalchemy**
* Fixes #865

### CODE REVIEW

**Comment by nateprewitt** [comment]
@techalchemy can we get a quick test that has a path with a space in it, just so we know this isn't regressed? Thanks!

**Comment by techalchemy** [comment]
Yes and I can add one for the other PR I just sent, but first I must sleep!

**Comment by techalchemy** [comment]
Sorry this took me so long @nateprewitt I totally forgot to do it let me know if you need anything from me on this or any of my other prs

**Comment by erinxocon** [comment]
Thanks @techalchemy!

**Pull request merged**
