### PR TITLE
package and distribute via setup.cfg

### PR DESCRIPTION
**Pull request by 4383**
Hey!

## Overview
Latest version of setuptools come with setup.cfg configuration. This pull request introduce this new pratice.

## Benefits
- keep pipenv up-to-date with the latest python packaging best practices
- decreases setup.py verbosity
- extract configuration of python code
- improve version management

## Changes introduced
- introduce latest best practices for python packaging
- extract version number from package meta or from configuration file (final install or develop install)
- manage requirements based on python version with more pythonic way
- manage publish and upload via Makefile
- dynamicaly generate Makefile helping message

Bye!

### CODE REVIEW

**Comment by 4383** [comment]
Do you want I squash my commits?

**Comment by nateprewitt** [comment]
@4383 if you wouldn't mind squashing, that would be great. This is a PR I'm going to delegate to Kenneth because he's probably got an opinion. Thanks for taking the time to put this together!

**Comment by 4383** [comment]
@nateprewitt commits squashed!

**Comment by 4383** [comment]
fixing conflict introduced by v8.3.0

**Comment by kennethreitz** [comment]
Not happening — requires modern setuptools, which people don't always have. I don't consider this best practice (yet), but we'll get there, hopefully within the next year.

**Pull request closed without merging**
