### PR TITLE
Fixes terminal size not being set properly

### PR DESCRIPTION
**Pull request by spiliopoulos**
See at http://pexpect.sourceforge.net/pexpect.html the documentation
of interact. I include here for easy reference

  | Note that if you change the window size of the parent the SIGWINCH
  | signal will not be passed through to the child.

### CODE REVIEW

**Comment by kennethreitz** [comment]
this looks good!

**Comment by spiliopoulos** [comment]
Although I have still not used this package extensively, it seems it will be really helpful.
Thank you for this excellent contribution.

**Comment by kennethreitz** [comment]
did some cleanup

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/pipenv/commit/e6f09f8c3bd143ee22e6eeed7ecc07eb5c4884b1

**Comment by kennethreitz** [comment]
released!

**Pull request merged**
