### PR TITLE
Handle the directory name with whitespaces properly (#228)

### LINKED ISSUE #228: Cannot install a wheel package in a directory with whitespaces
### Summary

- If the name of current working directory contains the whitespaces
- You won't be able to install a package with [the wheel format](https://www.python.org/dev/peps/pep-0427/).

This bug occurs regardless of the value of `PIPENV_VENV_IN_PROJECT` environment variable.

### How to reproduce this error
Please comment if you cannot reproduce the error.

```console
$ mkdir 'directory with spaces'
$ cd 'directory with spaces/'


$ pipenv --three
Creating a Pipfile for this project...
Creating a virtualenv for this project...
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/simnalamburt/.local/share/virtualenvs/directory with spaces/bin/python3
Also creating executable in /home/simnalamburt/.local/share/virtualenvs/directory with spaces/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location:


$ pipenv install numpy
Creating a virtualenv for this project...
⠋Using base prefix '/usr'
New python executable in /home/simnalamburt/.local/share/virtualenvs/directory with spaces/bin/python
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python3.6/site-packages/virtualenv.py", line 1370, in install_python
    os.symlink(py_executable_base, full_pth)
FileExistsError: [Errno 17] File exists: 'python' -> '/home/simnalamburt/.local/share/virtualenvs/directory with spaces/bin/python3.6'

Virtualenv location:
Installing numpy...
Collecting numpy
  Using cached numpy-1.12.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy

Error:  An error occurred while installing numpy!
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/numpy-1.12.0.dist-info'
```
screenshot
*(Click to see the screenshot)*

### My Environment
I could reproduce the error in multiple environments. Please comment if you want more information.

```console
$ uname -a
Linux 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux
$ python3 --version
Python 3.6.0
$ pipenv --version
pipenv, version 3.4.1
```
```console
$ uname -a
Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
$ python3 --version
Python 3.6.0
$ pipenv --version
pipenv, version 3.4.1
```

### PR DESCRIPTION
**Pull request by simnalamburt**
Closes #228. Please review and comment. Thanks!

Use the command below to try patched version of pipenv.
```
pip install git+https://github.com/simnalamburt/pipenv.git@plan-a
```

### CODE REVIEW

**Comment by nateprewitt** [comment]
Hey @simnalamburt, thanks for taking the time to put this together. This issue was researched fairly extensively when it originally cropped up in #51. As the issue you linked to in the other thread (pypa/pip#923) notes, this is a problem with virtualenv.

As I noted [here](https://github.com/kennethreitz/pipenv/issues/51#issuecomment-275316816), trying to run an executable with spaces in the path will not work because the linux kernel parses the first space as the end of the command, and everything that follows is processed as a parameter. This issue (pypa/virtualenv/#53) has been open in virtualenv for nearly 6 years.

As for this patch, If start a fresh pipenv project with spaces, and then run `pipenv install numpy` as you showed in your example, I still receive `/bin/sh: /bin/pip: No such file or directory`. This is because the shebangs in the files created by virtualenv are all in the form `#!"/Users/pipenv/.local/share/virtualenvs/test with spaces/bin/python"`. When you run a command like `pip install` it calls a bash script in the /bin/ directory (`pip`) which has a shebang bound to the absolute path of the python version is needs to use. Without being able to modify all shebangs in the directory every time we make a change, we can't really guarantee any form of stability.

Due to the fact that both pip and virtualenv have had issues opened for multiple years about this, without resolution, I'm hesitant to introduce a patch that doesn't seem to work universally and makes breaking API changes. For those reasons, I don't think we're properly equipped to address this right now. If you find more information on a fix upstream in both pip and virtualenv, I'll gladly look at it. Thanks again for spending time researching this.

**Comment by simnalamburt** [comment]
@nateprewitt Did you really tried the patched version of pipenv? With this pull request being merged, the python executable won't contain whitespaces in its file path. It'll be like this: `/Users/username/.local/share/virtualenvs/test-with-spaces/bin/python`

Please try again with the command below:
```bash
pip install --upgrade git+https://github.com/simnalamburt/pipenv.git@plan-a
```

**Comment by nateprewitt** [comment]
@simnalamburt, my apologies, you're correct. There was something about my environment earlier that was experiencing conflict.

So that puts us at whether we're ready to consider a 4.0 jump. This will break previously created virtualenvs that were casing specific or used anything other than dashes as a separator. `Test With Spaces`, `test_with spaces`, `Test.With.Spaces` and `test-with-spaces` will now all be the same virtualenv. We'll need to make sure we provide documentation about that since it seems like it could be a stumbling block.

This will also provide an expectation for directories with spaces to work properly, however with `PIPENV_VENV_IN_PROJECT` this is still broken. It would be nice if we could make this solution work uniformly but that requires changing the project directory. I'd like @kennethreitz to sign off on this before we move forward, and we'll likely need to open a PR against a future 4.0.0 branch while we round up some of the other breaking changes that need to be queued up.

**Comment by simnalamburt** [comment]
@nateprewitt Hi! Thank you for reviewing my PR

> `Test With Spaces`, `test_with spaces`, `Test.With.Spaces` and `test-with-spaces` will now all be the same virtualenv.

I'll come back with the new solution which solves the problem that you said. If this PR breaks the backward compatibility, I'll solve as many problem as possible with a single breakage.

**Comment by ChristopherRabotin** [comment]
When will this be on PyPi? I encountered this very frustrating issue today. Regardless, thanks a lot for fixing this.

**Comment by nateprewitt** [comment]
Hey @ChristopherRabotin, I'm hoping to get a release (3.5.0) out in the next week, but can't make any promises. There's a few other features/bug fixes that are close to finished but not ready to merge.

In the meantime, if this is a critical bug fix for you, you can always install pipenv with `pip install git+https://github.com/kennethreitz/pipenv.git#egg=pipenv` to get the current HEAD of our master branch. I wouldn't recommend this as a permanent solution, but it will keep you going for the next few days.

**Pull request closed without merging**
