### PR TITLE
fix for #886

### LINKED ISSUE #886: Not able to use a remote url for --requirements
Take this example:

```
# pipenv install -r https://raw.githubusercontent.com/odoo/odoo/10.0/requirements.txt
Creating a virtualenv for this project…
⠋New python executable in /root/.local/share/virtualenvs/app-4PlAip0Q/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1744, in install
    import_requirements(r=project.path_to(requirements), dev=dev)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 234, in import_requirements
    assert os.path.isfile(r)
AssertionError
```

However, `pip install -r https://raw.githubusercontent.com/odoo/odoo/10.0/requirements.txt` works perfectly. I'd expect pipenv's version to work fine too.

### PR DESCRIPTION
**Pull request by Dreamersoul**
This should fix #886, however i am not sure if this is the right way to do this! haha
if something needs to be changed or fixed please let me know! this is my first time contributing here so i am expecting that i did something wrong.
Thanks for this amazing project btw

### CODE REVIEW

**Comment by erinxocon** [comment]
Hi @Dreamersoul!  Thanks for the PR!  Can you write a test for this before I merge it?

**Comment by erinxocon** [comment]
This also now has some conflicts.  Can you address these before I merge them?

**Comment by Dreamersoul** [comment]
fixing the conflicts right now. I can test the utils functions i added but i dont know how to approach testing the functionality added to the cli, do you have a suggestion?

**Comment by erinxocon** [comment]
Hmmm I'll think of a way and get back to you.  Going to merge this for now but leave this branch open,

**Comment by Dreamersoul** [comment]
thank you, i have added the utils test for now

**Comment by erinxocon** [comment]
@Dreamersoul Did I merge this before that test got included?  If not can you submit a test?  Or was this the unrelated test to the other PR!  A lot going on right now.

**Comment by Dreamersoul** [comment]
This was merged before the tests were submitted, i have submitted the tests for the Utils functions. but i am still trying to figure out a way to test the cli function
so the only thing missing is testing if a remote requirements.txt file gets installed. Any suggestions?

**Comment by erinxocon** [comment]
hmm I'll have to get back to you after work today!

**Comment by nateprewitt** [comment]
@Dreamersoul I've pushed 3688148a adding a `requirements.txt` we have control over. Feel free to use `https://github.com/kennethreitz/pipenv/blob/3688148ac7cfecefb085c474b092c31d791952c1/tests/test_artifacts/requirements.txt` as the remote URL used in the test. You can use the scaffolding you see in the other integration tests and run `pipenv install -r https://github.com/kennethreitz/pipenv/blob/3688148ac7cfecefb085c474b092c31d791952c1/tests/test_artifacts/requirements.txt` to test that `requests` and `records` are installed at the expected versions.

For posterity, these kinds of tests are bad and prone to failure, we should be doing less of them. In a perfect world where time was unlimited, we'd set up an internal server that we can spin up and down in the testing structure and then do a request to a URL on the localhost, avoiding the external network call. That's likely to be a significant endeavor though.

**Comment by Dreamersoul** [comment]
@nateprewitt thank you so much for the detailed response i will take a look at this when i get off work and have some time :) should be done by the end of this week
should we open an issue for this test so that we can discuss it there or should i just submit a PR when im done?

also i totally agree with the internal server part, maybe in the far future we can setup a docker container to host everything that network related tests need

**Comment by nateprewitt** [comment]
@Dreamersoul let's just open a PR when you have an initial concept and we can proof it from there.

**Pull request merged**
