### PR TITLE
Non editable vcs fix

### PR DESCRIPTION
**Pull request by techalchemy**
See #806 - issue is easily reproducible

### CODE REVIEW

**Comment by erinxocon** [comment]
@techalchemy Thanks for the fix!  Can you write or update the test suite for this bug?

**Comment by techalchemy** [comment]
but, what about being lazy :(

**Comment by erinxocon** [comment]
@techalchemy as awesome as being lazy is, having a well tested master python tool is pretty cool too right :)

**Comment by techalchemy** [comment]
for sure, glad to see you policing it :) I'll write some tests for it in the morning after I confirm that it also fixes the alternate variant of the issue I just read in full

**Pull request merged**
