### PR TITLE
Add PIPENV_NOSPIN option for cleaner build logs

### PR DESCRIPTION
**Pull request by jacebrowning**
I would like to be able to clean up this noise on CircleCI:

screen shot 2017-02-02 at 1 02 59 pm

### CODE REVIEW

**Comment by jacebrowning** [comment]
@kennethreitz Thoughts on this?

It probably makes more sense to add a `spinner.disable()` API in blindspin, but this is start...

**Comment by nateprewitt** [comment]
I can see the desire to have cleaner logs, but I don't think we need another variable specifically for the spinner. It's more surface area for the user to have to worry about for a pretty specific edge case.

If Kenneth wants to entertain this, I think there are two possibly simpler options:
 * a `PIPENV_CLEAN` (or `PIPENV_NOFUN` 😉)  that replaces and encapsulates both `PIPENV_COLORBLIND` and `PIPENV_NOSPIN`
* placing the spinner inside of a `if not bare` check to actually leverage our `--bare` argument.

**Comment by kennethreitz** [comment]
colorblind can disable the spinnner too.

**Comment by jacebrowning** [comment]
@kennethreitz But I love the colors! 😄

I'll push a change that uses the same environment variable for you to consider.

**Comment by kennethreitz** [comment]
this change is sane, i'll keep it.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
released!

**Comment by kennethreitz** [comment]
might be refactored in the future

**Pull request merged**
