### PR TITLE
Fix is_file

### PR DESCRIPTION
**Pull request by krismolendyke**
Related to #926, `utils.is_file` seems like it should check not only that a file exists but that a file is a file and not a directory.

I added some tests for `utils.is_file` but I don't have any pytest experience so please let me know if there's a better way to accomplish that logic.

### CODE REVIEW

**Comment by nateprewitt** [comment]
@techalchemy, I think you've got a good grasp on most of the places is_file is used. This seems sensical to me, but I want to double check this won't have unintended consequences. Any thoughts?

**Comment by techalchemy** [comment]
WE can't actually do this unless we add an additional check everywhere we check for `is_file` to see if something is a directory.  The reason is that often someone attempts to install something such as `-e ../package/` which would install a package in a relative path using its `setup.py`. See for instance #540 -- but if you want to make the naming more accurate we can make the function name `is_path` or something

**Comment by techalchemy** [comment]
The fact that all the tests pass with this change is concerning, I guess I need to add one to cover this condition

**Comment by krismolendyke** [comment]
That was my concern, too, and why in #926 i didn't push this change into `utils.is_file`.  Happy to take a different approach here but I still need figure out a way to discern between filesystem directories and Python packages.  Maybe we are back in an `importlib` or `__init__.py` sniffing scenario?

**Comment by techalchemy** [comment]
What is driving the need to make this distinction?  I'm not understanding the issue you are attempting to fix here

**Comment by krismolendyke** [comment]
My particular issue stems from this logic https://github.com/kennethreitz/pipenv/blob/9c4b68605ce60c4650b30289cabcf941fa7e5fa7/pipenv/project.py#L72.

As mentioned in #926 I have a project that requires the `ansible` package _and_ has a project root directory named `ansible/`.  Since that logic detects the `ansible/` directory as a file, it does not add the legitimate `ansible` package from my `Pipfile` to the package list.

**Comment by krismolendyke** [comment]
I should note that the `ansible/` directory is nothing directly related to any Python packages.  It is simply a place where playbooks and other Ansible stuff is kept.  It's nothing like an editable Python package installation.

**Comment by techalchemy** [comment]
Do you have an issue open for this? I'm not clear on how pipenv is detecting your project root directory name is ansible? Can you provide instructions for how to replicate this?

**Comment by techalchemy** [comment]
For example I created a new project directory called ansible and ran `pipenv install ansible` without issue.

```pycon
    >>> project.project_directory
    '/tmp/ansible'

    >>> project.packages
    {'ansible': '*'}
```

```console
 ◰³ tempenv-522680565567  /t/ansible  cat Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
ansible = "*"

[dev-packages]

 ◰³ tempenv-522680565567  /t/ansible  pipenv install
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (114e81)!
Installing dependencies from Pipfile.lock (114e81)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 
```

**Comment by krismolendyke** [comment]
It's a work project so I can't share 😉 but the layout is similar to:

```sh
$ ll -R project-root
total 0
-rw-r--r--  1 kris  staff     0B Oct 18 16:49 Pipfile
-rw-r--r--  1 kris  staff     0B Oct 18 16:49 Pipfile.lock
drwxr-xr-x  2 kris  staff    68B Oct 18 16:49 ansible/
```

More generally, this is a problem whenever a Python package name parsed from a section of the `Pipfile` matches the name of a directory immediately next to `Pipfile`.  I can work up a failing test case later.

If in [your example](https://github.com/kennethreitz/pipenv/pull/936#issuecomment-337723560) you simply made `ansible` an immediate sub-directory of the project root, I think the issue will present itself.

**Comment by krismolendyke** [comment]
I'm going to close this because it seems like mucking with `utils.is_file` is not the best approach.  I'll open another pull request w/ a more clear failing test case that illustrates the issue.

Thanks for the discussion.

**Comment by techalchemy** [comment]
Gotcha.  I mainly have two concerns and I am not sure which approach is best

* I want to be sure that people who intend to install a local package can do that (e.g. pipenv install xyz.zip or pipenv install xyz.whl), as well as local folders which are packages (maybe that requires an additional check for directory paths or enforces ./ and ../ on those paths which are directories?)
* Alternatively we could take a different approach and alter the way projects spit back their package lists?
* is_file is used in a lot of places, but perhaps should be renamed 'is_local_path' or something similar... it was never really meant to test remote URIs
* Thanks to you as well for your patience, this is a situation I hadn't considered but seems like a valid use case, I'm just not sure about the optimal approach

**Comment by krismolendyke** [comment]
No sweat.  I have some thoughts on those topics and others that I'll let bake a bit longer.  In the meantime I have a local fix for my immediate issue.

**Comment by techalchemy** [comment]
Excellent! I’d be glad to hear them and continue the discussion on how to handle this.  If you don’t have an issue opened on this I’ll go ahead and create one to track this

**Comment by krismolendyke** [comment]
🆒  go ahead and create an issue, thanks.  I'll collect my thoughts there.  If I had to boil this down I'd say that the basic issue is distinguishing local/editable "installations" of Python packages from identically named "plain" filesystem files/directories.

**Pull request closed without merging**
